.github/workflows/release.yml
docker-compose.yml
docs/nginx.conf
src/main/java/com/example/solidconnection/config/cors/CorsPropertiesConfig.java
src/main/java/com/example/solidconnection/config/cors/WebConfig.java
src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java

도메인 전환에 따라 하드코딩 되어 있는 url을 수정했습니다. 이후 수정이 필요해 보입니다.
Nginx를 도커로 올리지 않고 서버에서 상시로 작동하게 변경했습니다. 이에 따라 미사용 `nginx.conf` 파일을 docs로 이동했고 workflow, `docker-compose.yml`을 수정했습니다.
workflow의 `docker-compose` -> `docker compose`로 명령이 변경되어 최신화 했습니다.

chore: 호스팅 도메인 변경과 nginx 제거에 따른 전환

---

src/main/java/com/example/solidconnection/application/domain/Application.java
src/test/java/com/example/solidconnection/e2e/SignUpTest.java
src/test/java/com/example/solidconnection/unit/repository/CommentRepositoryTest.java

- related to: #111 
실패하는 테스트 코드들을 수정했습니다.
1. TINYINT(1)에 대해서 MySQL과 H2의 환경이 달라 문제가 발생했었습니다.
문제 해결 과정을 디스커션에 정리해두었습니다 https://github.com/solid-connection/solid-connect-server/discussions/117
2. `CommentRepository.findCommentTreeByPostId()`의 단위 테스트 코드가 profile 변경에 의해 깨졌습니다.
H2은 MySQL과 달리 RECURSIVE 문이 동작하지 않으므로 MySQL을 사용하기 위해서 local 로 profile을 지정해놨는데,
이 profile 이름을 dev 로 바꿈에 따라서 깨졌던 것입니다.
ActiveProfile을 dev 로 바꿔 테스트 통과시켰습니다.
(하지만 이렇게 profile이나 db의 종류에 의존하는 테스트코드가 베스트라고 생각하진 않습니다..😔)
위 두가지 문제 모두, test 환경에서는 H2을, 개발 환경에서는 MySQL을 사용하기에 생기는 문제입니다.
이를 해결하기 위해서 따로 이슈를 팠으며, https://github.com/solid-connection/solid-connect-server/issues/119
이 PR에서는 우선 테스트 코드가 다 통과하게 하는 것이 목적이었기에 여기까지 하고 PR 올립니다!

fix: 전체 테스트 코드 통과되도록 수정

---

build.gradle
src/test/java/com/example/solidconnection/concurrency/PostLikeCountConcurrencyTest.java
src/test/java/com/example/solidconnection/concurrency/PostViewCountConcurrencyTest.java
src/test/java/com/example/solidconnection/concurrency/ThunderingHerdTest.java
src/test/java/com/example/solidconnection/database/DatabaseConnectionTest.java
src/test/java/com/example/solidconnection/database/RedisConnectionTest.java
src/test/java/com/example/solidconnection/e2e/BaseEndToEndTest.java
src/test/java/com/example/solidconnection/e2e/SignUpTest.java
src/test/java/com/example/solidconnection/e2e/UniversityDataSetUpEndToEndTest.java
src/test/java/com/example/solidconnection/support/DatabaseCleaner.java
src/test/java/com/example/solidconnection/support/MySQLTestContainer.java
src/test/java/com/example/solidconnection/support/RedisTestContainer.java
src/test/java/com/example/solidconnection/support/TestContainerDataJpaTest.java
src/test/java/com/example/solidconnection/support/TestContainerSpringBootTest.java
src/test/java/com/example/solidconnection/unit/repository/BoardRepositoryTest.java
src/test/java/com/example/solidconnection/unit/repository/CommentRepositoryTest.java
src/test/java/com/example/solidconnection/unit/repository/GpaScoreRepositoryTest.java
src/test/java/com/example/solidconnection/unit/repository/LanguageTestScoreRepositoryTest.java
src/test/java/com/example/solidconnection/unit/repository/PostLikeRepositoryTest.java
src/test/java/com/example/solidconnection/unit/repository/PostRepositoryTest.java

- resolves: #119 
테스트 컨테이너를 적용했습니다.
도입 배경 / 적용 방법은 위키에 정리해두었습니다.
https://github.com/solid-connection/solid-connect-server/wiki/TestContainers-도입기
테스트 실행 시간이 제 컴퓨터 기준 13s → 25s 로 늘어났습니다 🐢
하지만 위 위키에서 정리한 4가지 장점이, 테스트 실행 시간 증가로 인한 단점보다 더 크다고 생각합니다.
이에 대한 다른 분들의 생각을 듣고 싶습니다.
1/
❗️이 브랜치 pull 받아서, 본인 컴퓨터에서는 테스트 시간 얼마나 늘어났는지 알려주세요❗️
다른 분들이 불편할만큼 테스트 시간이 늘어난거라면 도입을 재고해봐야 할 것 같습니다😞
2/
그리고 '데이터베이스 연결 및 테이블 존재 여부 테스트'랑 '레디스 연결 및 작동 테스트'는
전체 테스트에 포함시키지 않도록 Disabled 어노테이션 달아줬습니다.
연결에 문제가 있다고 생각되시는 분들만 Disabled 해제하셔서 테스트하는게 좋을 것 다 생각했습니다.
괜찮나요?
3/
application-db.yml 에도 변경사항 생겨서 PR 만들어두었어요. https://github.com/solid-connection/solid-connect-secret/pull/3
이 코드 내용에 대해서 다 approve 하시면 
secret에 올려둔 PR머지 → 이 PR에 서브모듈 HEAD 업데이터 커밋 추가 → 머지
하겠습니다.

refactor: 테스트 컨테이너 적용

---

.github/ISSUE_TEMPLATE/refactor_request.md

chore: 리팩터링 이슈 템플릿 추가

---

src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java

- resolves: #157
어학점수 관련 통합 테스트 코드 추가하였습니다.
- GPA 점수 조회
- 어학 점수 조회
- GPA 등록
- 어학 점수 등록

test: 어학점수 관련 통합테스트 코드 추가

---

src/main/java/com/example/solidconnection/university/repository/UniversityInfoForApplyRepository.java
src/main/java/com/example/solidconnection/university/service/GeneralRecommendUniversities.java
src/main/java/com/example/solidconnection/university/service/GeneralUniversityRecommendService.java
src/main/java/com/example/solidconnection/university/service/UniversityRecommendService.java
src/test/java/com/example/solidconnection/e2e/UniversityRecommendTest.java
src/test/java/com/example/solidconnection/university/service/GeneralRecommendUniversitiesTest.java
src/test/java/com/example/solidconnection/university/service/GeneralUniversityRecommendServiceTest.java
src/test/java/com/example/solidconnection/university/service/UniversityRecommendServiceTest.java

- resolves: #169
해당 학기에 열린 대학들 중 랜덤하게 가져오도록 변경했습니다.
특이사항은 코멘트에서 더 설명할게요!

refactor: 공통 추천 대학 로직 변경

---

src/test/java/com/example/solidconnection/board/service/BoardServiceTest.java
src/test/java/com/example/solidconnection/support/integration/BaseIntegrationTest.java

- resolves: #174
게시글 관련 통합 테스트 코드 추가하였습니다.
리뷰 요구사항 (선택)
작업을 하면서 느낀 게 현재 폴더구조에 board, post, comment가 있는데 전부 community 관련된 것들이더라구요. 특히 board에는 전체 게시글 조회하는 것만 있고 post에 게시글 생성, 단일조회, 수정, 삭제 등이 있는데 한 폴더에서 관리하는 게 더 좋을 거 같다는 생각이 드네요
추가로 게시글 전체 조회는 Page나 Slice 없이 그냥 List로 다 받아오던데 특별한 이유가 있는건가요?

test: 게시판 관련 통합테스트 코드 추가

---

src/main/java/com/example/solidconnection/auth/domain/TokenType.java
src/main/java/com/example/solidconnection/auth/service/AuthService.java
src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
src/main/java/com/example/solidconnection/auth/service/SignInService.java
src/main/java/com/example/solidconnection/auth/service/SignUpService.java
src/main/java/com/example/solidconnection/auth/service/SignUpTokenProvider.java
src/main/java/com/example/solidconnection/auth/service/TokenProvider.java
src/main/java/com/example/solidconnection/auth/service/TokenValidator.java
src/main/java/com/example/solidconnection/custom/security/filter/SignOutCheckFilter.java
src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
src/test/java/com/example/solidconnection/auth/service/SignUpTokenProviderTest.java
src/test/java/com/example/solidconnection/auth/service/TokenProviderTest.java
src/test/java/com/example/solidconnection/custom/security/filter/SignOutCheckFilterTest.java
src/test/java/com/example/solidconnection/e2e/ApplicantsQueryTest.java
src/test/java/com/example/solidconnection/e2e/MyPageTest.java
src/test/java/com/example/solidconnection/e2e/MyPageUpdateTest.java
src/test/java/com/example/solidconnection/e2e/SignInTest.java
src/test/java/com/example/solidconnection/e2e/SignUpTest.java
src/test/java/com/example/solidconnection/e2e/UniversityDetailTest.java
src/test/java/com/example/solidconnection/e2e/UniversityLikeTest.java
src/test/java/com/example/solidconnection/e2e/UniversityRecommendTest.java
src/test/java/com/example/solidconnection/e2e/UniversitySearchTest.java

https://github.com/solid-connection/solid-connect-server/pull/171#discussion_r1942132647 이 코멘트의 내용을 적용했습니다.
처음에는 리팩터링 우선순위가 높지 않다고 생각했었는데,. 
애플 로그인을 구현하며 SignUpToken 생성, 저장 로직을 구현하다보니 기존 함수들을 어떻게 사용해야할지 헷갈리더라고요😵‍💫
왜냐하면 기존에는 TokenProvider 에서 TokenType 을 인자로 받게하고, 
개발자가 이들을 함수를 조합해서 사용하게 했기 때문입니다.
**그래서 확장성은 고려되었지만, 각각의 타입에 맞는 제약은 개발자 개인에게 달려있었어요.**
게다가 위백님이 짚어주신 것처럼, '왜 여기에서는 오버로딩을 했지?'하는 의문도 들게 하고요.
그래서 TokenProvider 에서 각 토큰에 대한 로직을 캡슐화하도록 코드를 변경했습니다.
다른 특이사항은 코멘트로 남길게요!

refactor: TokenProvider 에서 각 토큰에 대한 로직을 캡슐화

---

src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java
src/main/java/com/example/solidconnection/score/domain/GpaScore.java
src/main/java/com/example/solidconnection/score/domain/LanguageTestScore.java
src/main/java/com/example/solidconnection/score/dto/GpaScoreRequest.java
src/main/java/com/example/solidconnection/score/dto/GpaScoreStatus.java
src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreRequest.java
src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreStatus.java
src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreStatusResponse.java
src/main/java/com/example/solidconnection/score/service/ScoreService.java
src/main/resources/db/migration/V4__remove_issue_date_columns.sql
src/test/java/com/example/solidconnection/application/service/ApplicationSubmissionServiceTest.java
src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java
src/test/java/com/example/solidconnection/support/integration/BaseIntegrationTest.java

- resolves: #180
GpaScore 과 LanguageTestScore 의 사용하지 않을 컬럼인 "issueDate"를 없앴습니다.
Flyway 이용하려고 Hibernate SQL 사용할 때 ddl-auto update로 사용하시나요? 저는 그렇게하면 서버가 안켜지고 create로 하니까 그냥 alter로 issueDate를 드랍하는 게 아니라 그냥 새 테이블 생성 쿼리문 주더라구요..
이번엔 컬럼 드랍하는 간단한 쿼리문이여서 그냥 제가 작성했습니다 @wibaek

refactor: 사용하지 않을 컬럼 제거

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/auth/dto/EmailSignInRequest.java
src/main/java/com/example/solidconnection/auth/dto/EmailSignUpTokenRequest.java
src/main/java/com/example/solidconnection/auth/dto/EmailSignUpTokenResponse.java
src/main/java/com/example/solidconnection/auth/dto/SignUpRequest.java
src/main/java/com/example/solidconnection/auth/service/CommonSignUpTokenProvider.java
src/main/java/com/example/solidconnection/auth/service/EmailSignInService.java
src/main/java/com/example/solidconnection/auth/service/EmailSignUpService.java
src/main/java/com/example/solidconnection/auth/service/EmailSignUpTokenProvider.java
src/main/java/com/example/solidconnection/auth/service/SignUpService.java
src/main/java/com/example/solidconnection/auth/service/oauth/AppleOAuthService.java
src/main/java/com/example/solidconnection/auth/service/oauth/KakaoOAuthService.java
src/main/java/com/example/solidconnection/auth/service/oauth/OAuthService.java
src/main/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpService.java
src/main/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpTokenProvider.java
src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
src/main/java/com/example/solidconnection/siteuser/domain/AuthType.java
src/main/java/com/example/solidconnection/siteuser/domain/SiteUser.java
src/main/resources/db/migration/V5__add_password_column.sql
src/test/java/com/example/solidconnection/auth/service/EmailSignInServiceTest.java
src/test/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpTokenProviderTest.java
src/test/java/com/example/solidconnection/e2e/SignUpTest.java

- resolves: #140 
이메일로 인증하는 것을 구현했습니다.
지금은 아주 엄청난 날림코드입니다... 🌪️
그래도 동작합니다...
제가 처음에 헷갈렸던 부분이 있었는데,
- `auth/email/sign-in` 이 이메일, 비밀번호를 받고 엑세스 코드와 리프레시 코드를 주는 api
- `auth/email/sign-up` 이 이메일, 비밀번호를 받고 signUpToken 을 주는 api 입니다.
그런데 마치 `auth/email/sign-up`가 이메일로 회원가입한다는 의미라고 오해하기 쉬운 것 같습니다.
api 들에 대해서 여러분들은 어떻게 생각하는지 리뷰로 듣고 싶습니다!!

feat: 이메일 인증 구현

---

src/main/java/com/example/solidconnection/application/dto/ApplyRequest.java
src/main/java/com/example/solidconnection/application/dto/UniversityChoiceRequest.java
src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java
src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
src/main/java/com/example/solidconnection/custom/validation/annotation/ValidUniversityChoice.java
src/main/java/com/example/solidconnection/custom/validation/validator/ValidUniversityChoiceValidator.java
src/test/java/com/example/solidconnection/application/service/ApplicationSubmissionServiceTest.java
src/test/java/com/example/solidconnection/custom/validation/validator/ValidUniversityChoiceValidatorTest.java

- resolves: #182 
기존 서비스 로직에 있던 대학 중복 선택 검증을 지우고 ConstraintValidator를 활용하여 DTO에서 검증하도록 변경하였습니다.
추가로 기존에 검증하지 않던 2지망 없이 1, 3지망만 선택하는 case의 예외처리도 ConstraintValidator에 추가하였습니다.
기존 코드가 잘 동작하는지 확인하고 있었는데 UniversityChoiceRequest의 1지망 @NotNull 어노테이션이 아예 동작하지 않는 것을 발견했었습니다. 왜그런지 구글링을 해보니 중첩 DTO일 때 저런 검증 어노테이션이 동작하려면
```
@Valid
UniversityChoiceRequest universityChoiceRequest
```
이런식으로 첫 DTO에 @Valid를 붙여야하는 것을 확인했습니다. 그동안 @Valid와 @Validated의 차이를 몰랐는데 이참에 알게되었네요. 이건 @Valid로만 적용가능하다고 합니다.
[중첩 DTO 관련 참고 자료](https://www.baeldung.com/spring-valid-vs-validated#using-valid-annotation-to-mark-nested-objects)
이 커스텀Validator 테스트 코드 작성방법을 몰라서 구글링을 해봤는데 자료가 잘 나오질 않네요. 혹시 다른 더 좋은 방안이 있다면 참고하겠습니다.
저는 [커스텀Validator 테스트 코드 관련 참고 자료](https://stackoverflow.com/questions/28768577/how-to-test-a-validator-which-implement …

refactor: 입력 형식과 관련된 검증은 Dto 내부에서 하게 한다.

---

src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
src/main/java/com/example/solidconnection/custom/security/authentication/JwtAuthentication.java
src/main/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilter.java
src/main/java/com/example/solidconnection/custom/security/mapper/SecurityRoleMapper.java
src/main/java/com/example/solidconnection/custom/security/userdetails/SecurityRoleMapper.java
src/main/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetails.java
src/main/java/com/example/solidconnection/type/Role.java
src/main/resources/db/migration/V6__add_admin_to_role_enum.sql
src/test/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilterTest.java
src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsServiceTest.java
src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsTest.java

- resolves: #190 
1. Role에 ADMIN 추가 및 Spring Security 권한 처리 추가하였습니다.
2. Security 필터 체인 실행 순서를 조정하였습니다.
3. 인증되지 않은 사용자가 관리자 api 호출 시 401, 권한 없는 사용자가 관리자 api 호출 시 403 에러를 반환하도록 하였습니다.
어드민 인가 관련 예외처리를 SecurityFilterChain에서 한 번에 하도록 하였는데 이 처리를 하는 필터인 ExceptionTranslationFilter는 커스텀으로 정의한 ExceptionHandlerFilter 필터보다 뒤에 있어 ExceptionHandlerFilter에서 예외를 처리할 수 없었습니다. 그래서 
`.addFilterAfter(exceptionHandlerFilter, ExceptionTranslationFilter.class)`
필터 순서를 ExceptionTranslationFilter 이후로 조정하였습니다.
[Security Filters](https://docs.spring.io/spring-security/reference/5.7/servlet/architecture.html#servlet-exceptiontranslationfilter)

feat: 관리자 role 추가

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/custom/resolver/AuthorizedUser.java
src/main/java/com/example/solidconnection/custom/resolver/AuthorizedUserResolver.java
src/main/java/com/example/solidconnection/custom/resolver/ExpiredToken.java
src/main/java/com/example/solidconnection/custom/resolver/ExpiredTokenResolver.java
src/main/java/com/example/solidconnection/custom/security/authentication/ExpiredTokenAuthentication.java
src/main/java/com/example/solidconnection/custom/security/provider/ExpiredTokenAuthenticationProvider.java
src/main/java/com/example/solidconnection/university/controller/UniversityController.java
src/test/java/com/example/solidconnection/custom/resolver/AuthorizedUserResolverTest.java

- resolves: #201
로그아웃에서 예외가 발생했습니다.
```
argument type mismatch
Controller [com.example.solidconnection.auth.controller.AuthController]
Method [public org.springframework.http.ResponseEntity<java.lang.Void> 
com.example.solidconnection.auth.controller.AuthController.signOut(com.example.solidconnection.custom.security.authentication.ExpiredTokenAuthentication)] with argument values:
[0] [type=com.example.solidconnection.custom.security.authentication.SiteUserAuthentication] 
[value=SiteUserAuthentication 
[Principal=com.example.solidconnection.custom.security.userdetails.SiteUserDetails@16a8d604, Credentials=
[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[ROLE_MENTEE]]]
```
로그아웃 컨트롤러에서 ExpiredTokenAuthentication 을 기대했는데 그건 없고,
SiteUserAuthentication 가 있다는 내용의 예외입니다.
제가 …

fix: 인증과 관련되어 리졸버와 컨트롤러 인자에서 발생한 이슈 해결

---

src/main/java/com/example/solidconnection/application/controller/ApplicationController.java
src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/community/board/controller/BoardController.java
src/main/java/com/example/solidconnection/community/comment/controller/CommentController.java
src/main/java/com/example/solidconnection/community/comment/dto/CommentCreateRequest.java
src/main/java/com/example/solidconnection/community/comment/service/CommentService.java
src/main/java/com/example/solidconnection/community/post/controller/PostController.java
src/main/java/com/example/solidconnection/community/post/dto/PostCreateRequest.java
src/main/java/com/example/solidconnection/community/post/service/PostCommandService.java
src/main/java/com/example/solidconnection/community/post/service/PostLikeService.java
src/main/java/com/example/solidconnection/community/post/service/PostQueryService.java
src/main/java/com/example/solidconnection/score/controller/ScoreController.java
src/main/java/com/example/solidconnection/score/dto/GpaScoreRequest.java
src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreRequest.java
src/main/java/com/example/solidconnection/score/service/ScoreService.java
src/test/java/com/example/solidconnection/community/comment/service/CommentServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostCommandServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostLikeServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostQueryServiceTest.java
src/test/java/com/example/solidconnection/concurrency/PostLikeCountConcurrencyTest.java
src/test/java/com/example/solidconnection/e2e/ApplicantsQueryTest.java
src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java

- resolves: #181 
회의에 나온 내용들을 반영했습니다😊
**URI 복수형 사용**
- 게시판 관련 uri를 `/communites/**` 에서 `/boards/**`로 변경
- 지원 관련 uri를 `/application/**` 에서 `/applications/**`로 변경
- 어학 성적 관련 uri를 `/score/languageTest/**`에서 `scores/language-tests/**`로 변경
- 학점 관련 uri를 `/score/gpa/**`에서 `/scores/gpas/**`로 변경
**request, response 변경**
- gpa 성적 등록, 어학 성적 등록 시 [파일 업로드 → url 제출]이 아니라 바로 파일을 업로드하도록 변경
- 댓글 작성 시 postId 함께 제출하도록 변경
- 게시글 작성 시 boardCode 함께 제출하도록 변경
- 게시판 조회(PostFindResponse)시 boardCode 함께 응답하도록 변경
**❗️조금 치명적인 이슈가 있습니다🥲❗️**
컨트롤러에서 SiteUser 를 인자로 받기 이전에는,
서비스 코드에서 직접 SiteUser 를 조회해와서, 다른 비지니스 로직들과 동일한 영속성 컨텍스트에 적재되었습니다.
그래서 Lazy Loading 을 사용할 수 있었어요.
하지만 지금은 컨트롤러에서 SiteUser를 가져오기 때문에, 
서비스 코드에서 이 SiteUser 는 영속 상태가 아니라 Lazy Loading이 적용되지 않습니다.
이 PR에서는 가장 간편한 해결방법으로 해결하긴 했는데, 추가로 논의가 필요할 것 같습니다.
이건 오늘 회의 …

refactor: 커뮤니티, 지원, 성적 관련 api 수정

---

src/main/java/com/example/solidconnection/university/domain/UniversityInfoForApply.java
src/main/resources/db/migration/V7__expand_details_column_length.sql

- resolves: #211
이번에 2025-2 시즌 파견대학을 추가하던중에 university_info_for_apply.details 필드의 기본값인 500을 초과하는 데이터가 있어 컬럼 길이 500 -> 1000으로 증가시켰습니다.

feat: university_info_for_apply 테이블 details 컬럼 길이 증가

---

src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
src/main/java/com/example/solidconnection/custom/exception/CustomAccessDeniedHandler.java
src/main/java/com/example/solidconnection/custom/exception/CustomAuthenticationEntryPoint.java
src/main/java/com/example/solidconnection/custom/response/ErrorResponse.java
src/main/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilter.java
src/test/java/com/example/solidconnection/custom/exception/CustomAccessDeniedHandlerTest.java
src/test/java/com/example/solidconnection/custom/exception/CustomAuthenticationEntryPointTest.java
src/test/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilterTest.java

- resolves: #208
유효하지 않은 토큰으로 API 요청 시 JwtAuthenticationFilter에서 발생한 예외(CustomException 등)가 ExceptionHandlerFilter에서 잡히지 않고, WAS 기본 예외 처리로 넘어가면서 500 에러가 발생하는 문제가 있었습니다.
지난번 #192 pr에서 인증/인가 관련 예외처리를 잡지 못해 필터순서를 조정하니 jwtAuthenticationFilter 발생한 예외를 잡아줄 exceptionHandlerFilter가 jwtAuthenticationFilter보다 훨씬 뒤인 ExceptionTranslationFilter 뒤에 있어서 잡지 못하는 것이었습니다.
필터 순서를 원복하고, Spring Security의 기본 제공 기능인 AccessDeniedHandler와 AuthenticationEntryPoint를 활용해 인증/인가 예외를 처리하도록 변경했습니다.
CustomAuthenticationEntryPoint, CustomAccessDeniedHandler를 구현하여 예외 발생 시 일관된 JSON 응답이 내려가도록 했습니다.
일단 필터 순서변경만으로 인가 관련 예외 잡는 것과 jwtAuthenticationFilter 예외를 잡는 것을 동시에 해결하는 것이 어려울 거 같아 이 방식으로 구현을 했는데 추후 더 나은 해결책을 찾으면 그거로 적용해보도록 하겠습니다 🥲

fix: 유효하지 않은 토큰으로 api 요청 시 500 error 발생 버그 수정

---

.github/workflows/prod-cd.yml
.github/workflows/stage-cd.yml
src/main/java/com/example/solidconnection/community/board/controller/BoardController.java

* fix: 커뮤니티 글 목록 토큰 없이 안보이도록 수정
* chore: submodule 업데이트

[RELEASE] 250216 릴리즈

---

src/main/java/com/example/solidconnection/application/service/ApplicationQueryService.java
src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java

- resolves: #219
지원서 등록 후 조회 시 이전 데이터가 계속 캐싱되어 있는 현상이 발생하였습니다.
1. 캐시 키를 단일화 (`applications:all`)하여 관리
2. `@DefaultCacheOut` 적용하여 지원서 등록 시 캐시 자동 삭제
3. region/keyword 검색 및 isMine 표시는 당장 사용하지 않으므로 무시
- 캐싱 전략 재검토 필요 (TTL 조정, 검색 기능 추가 등)
임시조치로 해결한 것이어서 이에 대한 테스트코드는 일단 작성하지 않았는데 필요하면 추가하겠습니다!

fix: 지원 내역 조회 시 캐시 갱신 문제 임시 해결

---

.github/workflows/prod-cd.yml
.github/workflows/stage-cd.yml
Dockerfile
docker-compose.prod.yml
docker-compose.stage.yml

스테이지 서버에 돌아가는 app 의 profile이 prod 로 지정되는 이슈가 있었습니다.
cd 에서 `./gradlew bootJar -Dspring.profiles.active=stage`를 해주었음에도 
prod profile로 실행되는게 이상해서 코드를 더 봐보니, 
docker file 에서 추가적으로 profile을 prod로 지정하고 있었습니다.
이때 profile 이 덮어쓰기되어 prod로 실행되었습니다.
profile 을 한곳에서 지정하도록 Dockerfile에서 지정하는 부분은 없앴습니다.
stage 서버의 mysql을 처음에는 localhost에 설치했습니다.
그랬더니 [docker위에 동작하는 스프링 어플리케이션] → [host 의 mysql] 로의 통신이 되어서
도커 네트워크 설정이 복잡해지더라고요😓
심지어 커멘트로 직접 설정하는거라, 비슷한 상황에서 적용되기도 힘들 것 같다 생각했습니다.
위 이슈에서 보시다시피, stage의 인프라 구성과 prod의 구성이 100%일치하진 않습니다.
그래서 docker-compose 파일을 분리했습니다.
stage 서버는 prod 와 최대한 가은 환경이어야 한다고 생각해서 
처음에는 최대한 docker-compose도 하나로 가려고 했었는데요,
현실적으로 이들이 100% 일치하기는 어려우니까 분리를 하는게 맞다고 생각했습니다.
stage 서버도 prod처럼 그 자체만을 위한 db를 외부에 가지게 하는건 비효율적인 것 같습니다.
"최대한 비슷한 환경이되, 어느 정도 타협을 해야한다"는 생각이 들었습니다.

chore: stage, prod docker-compose 파일 분리

---

src/main/java/com/example/solidconnection/siteuser/controller/SiteUserController.java
src/main/java/com/example/solidconnection/siteuser/service/SiteUserService.java
src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java

- resolves: #226
PATCH 메서드에 따라 전송한 리소스만 변경되게 수정하였습니다.
파일이 empty인 상태일 때 굳이 예외를 던지기보단 변경을 안하는 게 클라이언트 입장에서 더 좋은 거 같아서 validateProfileImageNotEmpty 메서드는 그냥 지웠는데 괜찮을까요?

fix: 프로필 수정 API에서 닉네임, 이미지 부분 업데이트 가능하도록 수정

---

src/main/java/com/example/solidconnection/application/repository/ApplicationRepository.java
src/main/java/com/example/solidconnection/application/service/ApplicationQueryService.java
src/test/java/com/example/solidconnection/application/service/ApplicationQueryServiceTest.java

- resolves: #229
GET /applications API에서 유저의 이전 지원서까지 조회되는 오류가 있었습니다.
isDelete가 false인 것만 조회되도록 하여 최신 지원서만 조회되도록 수정하였습니다.

fix: 최신 지원서만 조회되도록 수정

---

.github/workflows/ci.yml
src/main/java/com/example/solidconnection/auth/client/AppleOAuthClientSecretProvider.java
src/main/java/com/example/solidconnection/config/client/AppleOAuthClientProperties.java
src/main/java/com/example/solidconnection/entity/common/BaseEntity.java
src/test/java/com/example/solidconnection/database/DatabaseConnectionTest.java
src/test/java/com/example/solidconnection/database/RedisConnectionTest.java
src/test/java/com/example/solidconnection/e2e/ApplicantsQueryTest.java
src/test/java/com/example/solidconnection/support/DatabaseCleaner.java
src/test/java/com/example/solidconnection/support/MySQLTestContainer.java
src/test/java/com/example/solidconnection/support/RedisTestContainer.java
src/test/java/com/example/solidconnection/support/TestContainerDataJpaTest.java
src/test/java/com/example/solidconnection/support/TestContainerSpringBootTest.java
src/test/resources/application.yml

- resolves: #111 
원래 목적은 ci 스크립트 작성이었는데,… 
ci 스크립트를 작성하고, 테스트들을 다 통과시키기 위해서는 세트로 발생하는 문제들이 꽤나 많았습니다🥲
❗️ **PR 디스크립션과 커밋 따라가시면 파악하기 쉬우실겁니다!** ❗️
1. [디스커션](https://github.com/solid-connection/solid-connect-server/discussions/257)에서 논의한대로 test를 위한 변수들을 **/src/test/resources/application.yml 파일로 분리**했습니다.
2. 위 과정에서 **애플 OAuth의 클라이언트 시크릿 만드는 부분의 코드를 변경**했습니다.
테스트 코드가 main/secret/AppleOAuthKey.p8 파일에 접근하지 못해서 테스트가 실패하는 문제가 있었는데,
동일하게 test/secret/ 경로에 AppleOAuthKey.p8 파일을 만들기보다, 다른 변수들처럼 yml 로 관리하는게 좋을 것 같아 바꿔줬습니다.
3. **redis test container 설정 코드를 변경**했습니다.
기존 설정이 잘못되어있더라고요🥲
이걸 왜 지금 알게 되었는지와, 어떻게 다시 설정했는지를 [디스커션](https://github.com/solid-connection/solid-connect-server/discussions/265)에 정리했습니다.
스프링의 환경변수인 Environment 에 대한 내용이 있으니 한번 읽어보셔도 도움될 것 같습니다.
4. 어플리케이션에서 초기화한 ZonedDateTime 과,
이를 MySQL DB에 …

chore: ci 스크립트 작성 및 ci 통과를 위한 코드 수정

---

.github/CODEOWNERS

GitHub Code owners 기능을 사용하여 이 레포에 올라오는 모든 PR의 리뷰어가 
위백님, 규혁님, 저로 자동 배정되게 했습니다😊
이 PR이 머지되면 적용됩니다.
ref. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
fork 레포 → 팀 레포로의 PR에는 리뷰어로 자동 배정되지만, 
fork 레포 → fork 레포로의 PR에는 (fork 레포에 write할 수 있게 추가되어있지 않는 한) 리뷰어로 배정되지 않습니다.
예를 들어 제가 제 fork 레포로의 PR을 만들었다고 해서, 위백님과 규혁님이 해당 PR의 리뷰어로 배정되진 않습니다.

chore: codeowners로 리뷰어 자동 배정되도록

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/auth/domain/TokenType.java
src/main/java/com/example/solidconnection/auth/dto/ReissueRequest.java
src/main/java/com/example/solidconnection/auth/service/AuthService.java
src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
src/main/java/com/example/solidconnection/util/JwtUtils.java
src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java

- resolves: #258 
분명 엑세스 토큰 재발급 로직이 있을텐데 왜 사용자가 만료가 빠르다고 느끼는가 싶어 코드를 봤더니
엑세스 로직에서 실수가 있었습니다 🤕
코멘트로 설명하겠습니다!
**그리고 몇가지 작은 리팩터링은 커밋을 따라가면 이해하시기 편하실겁니다~**
토큰도 Sting, subject도 String 형식이라 이런 실수가 발생했습니다.
Token 이라는 클래스를 만들면 이런 실수를 사전에 방지할 수 있을 것 같습니다.
그리고 Token 클래스가 필드로 subject를 가지게 하고,
`JwtAuthenticationFilter`에서 Token 객체를 생성할 때 subject를 초기화한다면
여러곳에서 JwtUtils.parseSubject() 를 호출하고있는 지금의 코드를 개선할 수 있을 것 같습니다!
(지금은 parseSubject 함수가 19군데에서 호출되고 있습니다.)

fix: 토큰 재발급 로직 수정

---

.github/workflows/dev-cd.yml

- resolves: #287
폴더명과 환경변수명의 환경 이름을 추가적으로 변경했습니다

chore: 워크플로우 경로, 환경변수 변경

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml
docker-compose.dev.yml
docker-compose.prod.yml

- resolves: #294 
config 파일을 같이 보내주는 것을 잊고 있었습니다 ㅎㅎ...

fix: Alloy 설정파일이 배포시에 업로드 되지 않는 오류 수정

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/auth/service/AuthService.java
src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java

- resolves: #298
- resolves: #99 
- 로그아웃 시, 엑세스 토큰에 해당하는 리프레시 토큰을 redis 로부터 삭제합니다.
- 탈퇴 시, 로그아웃합니다. 
- 리프레시 토큰 삭제
- 액세스 토큰을 블랙리스트에 추가
https://github.com/solid-connection/solid-connect-server/pull/297#pullrequestreview-2821601660 에서 이야기된 것처럼,
Authentication 으로부터 String accessToken을 추출하는것은 중복 코드가 2곳 뿐이며,
auth 패키지 이외에는 이 로직이 사용되는 곳이 없을 것이기에 ArgumentResolver로 만드는것은 과하다 생각했습니다.
그래서 우선은 private 메서드를 만들어주었습니다.
+) TODO 부분도 빠르게 작업해보겠습니다 🏃‍♀️🏃‍♀️

refactor: 로그아웃, 탈퇴 시 refresh 토큰을 삭제하도록

---

docker-compose.dev.yml
docker-compose.prod.yml

- resolves: #304
alloy.config라는 디렉토리가 알수없는 이유로 생성되어 있어 발생한 문제였습니다.
파일 scp시에 문제가 있었는데 
```
- name: Copy alloy config file to remote
uses: appleboy/scp-action@master
with:
host: ${{ secrets.DEV_HOST }}
username: ${{ secrets.DEV_USERNAME }}
key: ${{ secrets.DEV_PRIVATE_KEY }}
source: "./docs/config.alloy"
target: "/home/${{ secrets.DEV_USERNAME }}/solid-connection-dev/"
```
다음과 같이 전송하면 config.alloy가 이동되는게 아닌, docs/config.alloy 전체가 이동되는걸 알지 못했습니다.
strip_components 옵션으로 해결도 가능하나, 그냥 docs/ 경로를 유지하고 도커 파일을 수정해 이를 참고하게 했습니다

fix: Alloy 오류 수정

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java

- resolves: #310
위 내용을 적용한 아주 간단한 pr입니다 ㅎㅎ

refactor: 회원 탈퇴 API HTTP Method를 PATCH에서 DELETE로 변경

---

src/test/java/com/example/solidconnection/university/service/GeneralUniversityRecommendServiceTest.java
src/test/java/com/example/solidconnection/university/service/UniversityLikeServiceTest.java
src/test/java/com/example/solidconnection/university/service/UniversityRecommendServiceTest.java

- resolves: #312
기존 BaseIntegrationTest로 생성하던 테스트 데이터를 Fixture 메서드로 생성하도록 변경하였습니다.
추천 관련 통합테스트는 모든 대학들을 세팅해주는 게 좋은 거 같은데 어떻게 생각하시나요? 
generalUniversityRecommendService.init(); 이거 호출 전에 테스트 데이터가 6개 이상 없으면 바로 Out of Range 터지더라구요 그래서 BeforeEach로 지금 한 번에 생성해주고 있긴한데 더 좋은 방식이 있을까요? 🥲

refactor: 대학(추천, 좋아요) 통합 테스트 데이터 Fixture 메서드로 변경

---

src/test/java/com/example/solidconnection/admin/service/AdminGpaScoreServiceTest.java
src/test/java/com/example/solidconnection/admin/service/AdminLanguageTestScoreServiceTest.java
src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
src/test/java/com/example/solidconnection/auth/service/EmailSignInServiceTest.java
src/test/java/com/example/solidconnection/auth/service/SignInServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostCommandServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostLikeServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostQueryServiceTest.java
src/test/java/com/example/solidconnection/concurrency/PostLikeCountConcurrencyTest.java
src/test/java/com/example/solidconnection/concurrency/PostViewCountConcurrencyTest.java
src/test/java/com/example/solidconnection/concurrency/ThunderingHerdTest.java
src/test/java/com/example/solidconnection/custom/resolver/AuthorizedUserResolverTest.java
src/test/java/com/example/solidconnection/custom/security/aspect/AdminAuthorizationAspectTest.java
src/test/java/com/example/solidconnection/custom/security/provider/SiteUserAuthenticationProviderTest.java
src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsServiceTest.java
src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsTest.java
src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java
src/test/java/com/example/solidconnection/siteuser/fixture/SiteUserFixture.java
src/test/java/com/example/solidconnection/siteuser/fixture/SiteUserFixtureBuilder.java
src/test/java/com/example/solidconnection/siteuser/repository/SiteUserRepositoryTest.java
src/test/java/com/example/solidconnection/siteuser/service/MyPageServiceTest.java
src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java
src/test/java/com/example/solidconnection/university/service/UniversityLikeServiceTest.java
src/test/java/com/example/solidconnection/university/service/UniversityRecommendServiceTest.java

- resolves: #318
유저 관련 통합 테스트 데이터 fixture 메서드로 변경했습니다
쪼개기가 애매한 거 같아서 어쩌다보니 pr이 조금 커졌네요...
#275 때같은 문제가 이제 발생하지 않겠네요
1. 우선 첫 커밋만 확인해서 이런식으로 Fixture 만드는 거 괜찮은지만 먼저 피드백 해주시면 좋을 거 같습니다!
뒷 부분은 그냥 단순 노동이었습니다. 😅
2. 추가로 이야기해볼 만한 건 SiteUserRepositoryTest에서 @TestContainerDataJpaTest를 쓰고 있었는데 얘는 @ComponentScan이 안되는 거 같더라구요. 그래서 주석으로 달아두었는데
@TestContainerDataJpaTest + @Import 쓰기 vs @TestContainerSpringBootTest 중 어떤 걸로 해야할지 고민이 되었습니다!

refactor: 유저 관련 통합 테스트 데이터 fixture 메서드로 변경

---

src/test/java/com/example/solidconnection/admin/service/AdminGpaScoreServiceTest.java
src/test/java/com/example/solidconnection/admin/service/AdminLanguageTestScoreServiceTest.java
src/test/java/com/example/solidconnection/score/fixture/GpaScoreFixture.java
src/test/java/com/example/solidconnection/score/fixture/GpaScoreFixtureBuilder.java
src/test/java/com/example/solidconnection/score/fixture/LanguageTestScoreFixture.java
src/test/java/com/example/solidconnection/score/fixture/LanguageTestScoreFixtureBuilder.java
src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java

- resolves: #321
성적 관련 통합 테스트 데이터 fixture 메서드로 변경했습니다!
이제 커뮤니티랑 모의지원만 해결하면 끝이네요!
어드민쪽 조회 테스트 시 너무 자세히 검증하던 then절을 좀 간소화했습니다! size()정도만 검증해도 괜찮을까요?

refactor: 성적 관련 통합 테스트 데이터 fixture 메서드로 변경

---

src/main/java/com/example/solidconnection/news/domain/LikedNews.java
src/main/resources/db/migration/V21__create_liked_news_table.sql

- resolves: #356
소식지 좋아요 엔티티를 추가하였습니다!
```
@Column(name = "news_id")
private long newsId;
@Column(name = "site_user_id")
private long siteUserId;
```
name을 명시해주지 않으니까 
```
@UniqueConstraint(
name = "uk_liked_news_site_user_id_news_id",
columnNames = {"site_user_id", "news_id"}
)
```
JPA가 이를 인식하지 못해 별도로 추가해주었습니다!
혹시 로컬에서 이거 flyway validate 확인하는 법 알려주실 수 있나요?
우선 flyway 스크립트로 테이블 생성해보았을 땐 잘 작동하였습니다!

feat: 소식지 좋아요 엔티티 추가

---

src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
src/main/java/com/example/solidconnection/mentor/controller/MentoringController.java
src/main/java/com/example/solidconnection/mentor/domain/Mentor.java
src/main/java/com/example/solidconnection/mentor/domain/Mentoring.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringApplyRequest.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringApplyResponse.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringCheckResponse.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringConfirmRequest.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringConfirmResponse.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringCountResponse.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringListResponse.java
src/main/java/com/example/solidconnection/mentor/dto/MentoringResponse.java
src/main/java/com/example/solidconnection/mentor/repository/MentorRepository.java
src/main/java/com/example/solidconnection/mentor/repository/MentoringRepository.java
src/main/java/com/example/solidconnection/mentor/service/MentoringCommandService.java
src/main/java/com/example/solidconnection/mentor/service/MentoringQueryService.java
src/test/java/com/example/solidconnection/mentor/fixture/MentorFixture.java
src/test/java/com/example/solidconnection/mentor/fixture/MentorFixtureBuilder.java
src/test/java/com/example/solidconnection/mentor/fixture/MentoringFixture.java
src/test/java/com/example/solidconnection/mentor/fixture/MentoringFixtureBuilder.java
src/test/java/com/example/solidconnection/mentor/service/MentoringCommandServiceTest.java
src/test/java/com/example/solidconnection/mentor/service/MentoringQueryServiceTest.java

- resolves: #352
멘토링 관련 로직을 작성하였습니다. ~~도메인 특성 상 `Mentor` 와 엮이는데, 병합 시 충돌 해결하면 될 듯 합니다. 이전 PR이 병합되면 rebase해서 마저 작업 진행하겠습니다.~~
- (그럴 일은 없겠지만) 멘토링 확인을 거치지 않고 수락/거절을 하게 된다면 `checkedAt` 값을 수락/거절 시점으로  결정하였습니다.
- 추후 리팩토링할 때 URI의 snake_case를 kebab-case로 바꾸면 좋을 거 같습니다.

feat: 멘토링 관련 도메인 추가

---

src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
src/main/java/com/example/solidconnection/news/controller/NewsController.java
src/main/java/com/example/solidconnection/news/domain/LikedNews.java
src/main/java/com/example/solidconnection/news/dto/LikedNewsResponse.java
src/main/java/com/example/solidconnection/news/repository/LikedNewsRepository.java
src/main/java/com/example/solidconnection/news/service/NewsLikeService.java
src/test/java/com/example/solidconnection/news/service/NewsLikeServiceTest.java

- resolves: #376
소식지 좋아요 관련 기능을 추가했습니다!
기존 대학 지원 정보 좋아요 관련 기능을 최대한 참고하며 진행했습니다!
상태확인, 좋아요, 좋아요 취소에 대해 무얼 응답하면 좋을지에 대해 아직 확정이 나지 않아 우선은 모두 id와 좋아요중인지를 응답하는 방식으로 통일해두었습니다!
(사실 전 지금 방식도 괜찮은 거 같긴 한데 의견 남겨주시면 좋을 거 같습니다!)
소식지가 존재하지 않는 경우에 대해서는 따로 테스트 코드를 작성하지 않았습니다!
getNewsLikeStatus로 일단 해두긴 했는데 뭐가 적절한지 모르겠네요 기존 대학 지원 정보에서는 getIsLiked로 되어있었긴 합니다!

feat: 소식지 좋아요 기능 구현

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml

dev CD가 안돌아서 왜 그런가 봤더니... alloy 파일 경로를 수정 안했더라고요 🫨🫨

fix: cd 스크립트의 alloy 파일 경로 수정

---

src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
src/main/java/com/example/solidconnection/report/controller/ReportController.java
src/main/java/com/example/solidconnection/report/domain/ReasonType.java
src/main/java/com/example/solidconnection/report/domain/Report.java
src/main/java/com/example/solidconnection/report/domain/ReportType.java
src/main/java/com/example/solidconnection/report/domain/TargetType.java
src/main/java/com/example/solidconnection/report/dto/ReportRequest.java
src/main/java/com/example/solidconnection/report/repository/ReportRepository.java
src/main/java/com/example/solidconnection/report/service/ReportService.java
src/main/resources/db/migration/V24__create_report_table.sql
src/test/java/com/example/solidconnection/community/post/fixture/PostFixture.java
src/test/java/com/example/solidconnection/report/fixture/ReportFixture.java
src/test/java/com/example/solidconnection/report/fixture/ReportFixtureBuilder.java
src/test/java/com/example/solidconnection/report/service/ReportServiceTest.java

- resolves: #401 
앱 출시를 대비하기 위해, 우선 순위가 올라간 "신고" 기능을 구현합니다.
- 채팅에도 신고 기능이 들어갈 것으로 압니다. "확장성"을 고려하여, 아래 형식으로 구현했습니다.
- 사용자는 특정 리소스를 한번만 신고 가능해야 한다고 생각해서 unique key 걸어주었습니다!
- api PR 도 검토해주세요~ https://github.com/solid-connection/api-docs/pull/28

feat: 신고 기능 구현

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/auth/service/AccessToken.java
src/main/java/com/example/solidconnection/auth/service/AuthService.java
src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
src/main/java/com/example/solidconnection/auth/service/SignInService.java
src/main/java/com/example/solidconnection/auth/service/TokenProvider.java
src/main/java/com/example/solidconnection/auth/token/JwtTokenProvider.java
src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
src/test/java/com/example/solidconnection/auth/service/JwtTokenProviderTest.java
src/test/java/com/example/solidconnection/auth/service/TokenBlackListServiceTest.java

- resolves: #406 
프론트 개발자님이 멘토/멘티 탭 구현할 때 더 편하다 하셔서 추가합니다 🏃‍♀️
- AccessToken 생성자 파라미터 변경
- TokenProvider에 claim 으로 토큰 만드는 함수 생성
- 토큰 재발급 시에도 role을 포함하여 응답하도록 수정
디스코드에 말씀드린 "auth 패키지 대변경🧹" 관점에서 추가설명하자면,
이번에 AccessToken 생성 방법 변경으로 '토큰 재발급 함수'에 아래의 변경이 있었습니다.
```java
/* 전 */
AccessToken accessToken = authTokenProvider.toAccessToken(token);
/* 후 */
Subject subject = authTokenProvider.parseSubject(token);
long siteUserId = Long.parseLong(subject.value());
SiteUser siteUser = siteUserRepository.findById(siteUserId)
.orElseThrow(() -> new CustomException(USER_NOT_FOUND));
AccessToken accessToken = authTokenProvider.generateAccessToken(subject, siteUser.getRole());
```
**이 변경의 문제**
- AccessToken 생성 로직이 여러 곳에 흩어져 있어, 방식을 바꿀 때 각 위치를 모두 수정해야 했다.
- 기존의 authTokenProvider.toAccessToken(token)도 더 이상 사용할 …

feat: access token이 role을 cliam 으로 갖도록

---

src/main/java/com/example/solidconnection/mentor/controller/MentorController.java
src/main/java/com/example/solidconnection/mentor/dto/MentorMyPageResponse.java

- related: 419
멘토의 마이페이지 응답 GET api가 범용적으로 사용되도록, '합격 팁'을 포함하여 응답하게 합니다.
**AS-IS**
- 멘토의 마이페이지 미리보기 화면에서는 '합격 팁'이 존재하지 않아 내려주지 않았습니다.
**TO-BE**
- 멘토가 마이페이지를 수정할 때 보여주는 '마이페이지 상세 조회'에는 합격 팁이 존재합니다.
- 이들 api를 하나로 통일하기 위해 '마이페이지' GET 의 응답이 '합격 팁'을 추가합니다.
멘토/멘티 api 변경 회의에서 이야기 나온 🔽 부분을 적용했다 생각하시면 됩니다.
"페이지네이션이 중복 설정된 것" 을 삭제하는 것까지
이번 PR에서 포함해봅니다 🐒

refactor: 멘토의 마이페이지 응답에 '합격 팁' 추가

---

src/main/java/com/example/solidconnection/mentor/domain/Channel.java
src/main/java/com/example/solidconnection/mentor/domain/Mentor.java
src/test/java/com/example/solidconnection/mentor/service/MentorMyPageServiceTest.java

- resolves: #424 
멘토의 마이 페이지 수정 시, 채널을 변경할 때 'unique 제약조건 위반'이 발생했습니다.
Channels 엔티티를 보면 아시겠지만, mentor_id와 sequence 조합으로 unique 제약조건을 설정해둔 상태였습니다.
코드 자체만 봤을 때는 “🤔removeAll 후 add 를 하고 있으니, 문제가 없지 않나?” 싶었습니다.
```java
// 이전 코드
public void updateChannels(List<Channel> channels) {
this.channels.clear();
if (channels == null || channels.isEmpty()) {
return;
}
for (Channel channel : channels) {
channel.updateMentor(this);
this.channels.add(channel);
}
}
```
[Hibernate 공식 문서](https://docs.jboss.org/hibernate/orm/4.2/javadocs/org/hibernate/event/internal/AbstractFlushingEventListener.html)에도 컬렉션에 있어서는 delete 문이 먼저 실행된다고 되어있어, 원인을 파악하기 어려웠습니다..
진짜 문제는 기존의 코드에서는 new Channel()로 완전히 새로운 객체를 만들어 넣었다는 것이었습니다.
이때문에 4번인 insertion of collection elements 가 아니라 1번의 insert로 인식되어서 delete 보다 먼저 실행되었습니다.
이 문제를 …

fix: 채널 수정 시 유니크 제약 위반하지 않도록

---

src/test/java/com/example/solidconnection/chat/service/ChatServiceTest.java
src/test/java/com/example/solidconnection/websocket/WebSocketStompIntegrationTest.java

- resolves: #427 
WebSocket + STOMP 관련 테스트 코드와 메시지 송신 테스트를 작성하였습니다.
~~#423 이 머지되면 rebase 하고 머지하겠습니다 !~~
`ArgumentCaptor` 라는 걸 처음 써 봤는데요, 어색한 부분이 있다면 말씀해주세요 ~
WebSocket + STOMP 통합 테스트는 `chat` 도메인 하위가 아니라 따로 작성하였습니다.
추가할 테스트가 있는지

test: WebSocket 관련 테스트 코드 작성

---

src/main/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManager.java
src/main/java/com/example/solidconnection/auth/controller/config/RefreshTokenCookieProperties.java
src/test/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManagerTest.java
src/test/java/com/example/solidconnection/auth/controller/config/RefreshTokenCookiePropertiesTest.java
src/test/resources/application.yml

- resolves: #449
🔽 프론트 만옥님이 말씀하신 문제 상황입니다
▶️ 쿠키의 도메인이 일치하지 않아 발생한 문제입니다.
- 백엔드 도메인 : `api.stage.solid-connection.com`
- 프론트 도메인 : `www.stage.solid-connection.com`
▶️ 문제의 원인: 쿠키 정보를 세팅할 때, domain을 별도로 지정하지 않으면 
쿠키를 발급하는 서버의 도메인 (api.stage.xxx) 로 자동 설정된다고 합니다 😓
▶️ 추가 요구사항: 프론트엔드 만옥님의 요청으로, dev 서버의 api는 localhost 에서 테스트할 수 있게 해야합니다.
---
환경별로 나누어 문제를 해결합니다.
- prod 환경
- 엄격한 보안 필요
- Domain을 구체적으로 지정
- `Domain=.solid-connection.com; Path=/; HttpOnly; Secure; SameSite=Strict;`
- dev 환경
- localhost 에서도 쿠키 저장이 가능하도록, 크로스 사이트 허용 필요
- Domain을 생략 && SameSite=None 설정
- `Domain=api.stage.solid-connection.com;(생략 시, 자동으로 서버의 도메인 할당됨) Path=/; HttpOnly; Secure; SameSite=Node;`
추가 요구사항으로 https로 localhost에서 테스트할 수 있도록 cors 허용 리스트에 `https://localhost:3000` 을 추가합니다
시크릿 레포에도 PR 올렸습니다 🏃‍♀️ …

refactor: refreshToken 쿠키에서 환경별로 Domain 설정하도록

---

src/main/java/com/example/solidconnection/auth/controller/AuthController.java
src/main/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManager.java
src/main/java/com/example/solidconnection/auth/dto/ReissueRequest.java
src/main/java/com/example/solidconnection/auth/service/AuthService.java
src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
src/main/java/com/example/solidconnection/auth/service/SignInService.java
src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
src/test/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManagerTest.java
src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
src/test/java/com/example/solidconnection/websocket/WebSocketStompIntegrationTest.java

- resolves: #451 
- **AS-IS**
- Body에 refreshToken을 전달해야 했습니다.
- 하지만 '쿠키에 refreshToken을 저장'하도록 보안 정책이 바뀌었고, 
프론트엔드에서 브라우저의 쿠키에 접근할 수 없게 됨에 따라 이 방법이 불가능해졌습니다.
- **TO-BE**
- 쿠키의 refreshToken을 추출하여 accessToken을 재발급하도록 변경합니다.
사실 이 PR에 포함되는 범위는 아니지만...
authTokenProvider의 몇몇 함수를 고쳐 중복 코드를 없앴습니다.. 🙄🙄
어차피 auth 패키지 리팩터링하려 했으니 이정도는 괜찮겠지요? 호호..
커밋 따라가며 읽으시면 쉽습니다!
https://github.com/solid-connection/api-docs/pull/41 와 함께 머지합니다.

refactor: accessToken 재발급을 refreshToken 쿠키를 통해 하도록

---

src/main/java/com/example/solidconnection/chat/controller/ChatController.java
src/main/java/com/example/solidconnection/chat/service/ChatService.java
src/test/java/com/example/solidconnection/chat/service/ChatServiceTest.java

- resolves: #456
만욱님께서 요청해주신 기능을 구현한 pr입니다.
[bruno 관련](https://github.com/solid-connection/api-docs/pull/43)

feat: 채팅방 partner 정보를 조회하는 API 추가

---

src/main/java/com/example/solidconnection/mentor/dto/MentoringForMentorResponse.java

- resolves: #462 
https://github.com/solid-connection/api-docs/pull/45
프론트 만옥님의 요청에 따라
멘토가 멘토링 목록을 조회할 때, `isConfirmed` 대신 `verifyStatus`를 응답하게 합니다.
Dto만 수정된 간단한 수정입니다🤗

refactor: 멘토의 멘토링 목록 조회 시 isConfirmed 대신 verifyStatus를 응답하도록

---

src/main/java/com/example/solidconnection/university/controller/UnivApplyInfoController.java
src/main/java/com/example/solidconnection/university/domain/LanguageTestType.java
src/main/java/com/example/solidconnection/university/dto/UnivApplyInfoFilterSearchRequest.java
src/main/java/com/example/solidconnection/university/repository/UniversityRepository.java
src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepository.java
src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepositoryImpl.java
src/main/java/com/example/solidconnection/university/service/UnivApplyInfoQueryService.java
src/test/java/com/example/solidconnection/university/service/UnivApplyInfoQueryServiceTest.java

- resolves: #469
수경님과 회의한 내용에 따라, 대학지원정보 필터링 검색 기능을 수정합니다.
어떻게 API 기획이 바뀌었는지는 api-docs PR에 자세히 나와있습니다🤗
https://github.com/solid-connection/api-docs/pull/48
코멘트로 남겨두겠습니다!

refactor: 기획 변경에 맞게 필터링 검색 기능 수정

---

src/main/java/com/example/solidconnection/university/controller/UnivApplyInfoController.java
src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepository.java
src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepositoryImpl.java
src/main/java/com/example/solidconnection/university/service/UnivApplyInfoQueryService.java
src/test/java/com/example/solidconnection/university/fixture/UnivApplyInfoFixture.java
src/test/java/com/example/solidconnection/university/fixture/UniversityFixture.java
src/test/java/com/example/solidconnection/university/service/UnivApplyInfoQueryServiceTest.java

- resolves: #470 
텍스트로 대학지원정보를 검색할 수 있는 API를 구현했습니다.
이슈에 자세한 정책 내용 나와있습니다 🫡
코멘트로 남겨두겠습니다!

feat: 대학지원정보 텍스트 검색 기능 구현

---

src/main/java/com/example/solidconnection/chat/dto/ChatRoomData.java
src/main/java/com/example/solidconnection/chat/dto/UnreadCountDto.java
src/main/java/com/example/solidconnection/chat/repository/ChatMessageRepository.java
src/main/java/com/example/solidconnection/chat/repository/ChatRoomRepository.java
src/main/java/com/example/solidconnection/chat/service/ChatService.java
src/main/java/com/example/solidconnection/siteuser/repository/SiteUserRepository.java

- resolves: #458
채팅방 조회 n + 1 문제를 개선하였습니다.
- 1 + 3N 쿼리 발생
- 사용자 조회 (1개)
- 채팅방 조회 (1개)
- 각 채팅방별 반복 (3N개) -> 최신 메시지 조회(N), 사용자 조회(N), 안읽은 메시지 수 조회(N)
- 참가자 배치 조회(1개) - @BatchSize(10)
- 5개 쿼리 발생(고정)
- 사용자 조회 (1개) - 동일
- 채팅방 + 참가자 한번에 조회 (1개)
- 최신 메시지들 배치 조회 (1개)
- 안읽은 메시지 수들 배치 조회 (1개)
- 파트너 사용자들 배치 조회 (1개)
1. JOIN FETCH 활용
기존: 채팅방 조회 → 참가자 개별 조회 (N+1)
개선: 채팅방 + 참가자 한번에 조회
2. 배치 활용:
기존: 각 채팅방별로 개별 쿼리 (× 3)
개선: WHERE ... IN (chatRoomIds) 로 배치 처리
3. 메모리 + Map 활용:
DB에서 가져온 데이터를 Map으로 변환 후 메모리에서 조합
추가 DB 접근 없이 Response 생성
채팅방 만약 20개였다면 62개(1 + 1 + 3N + 2)가 나가던 쿼리가 5개로 줄어들었습니다.

refactor: 채팅방 관련 n + 1 문제 개선

---

src/main/java/com/example/solidconnection/mentor/controller/MentoringForMenteeController.java
src/main/java/com/example/solidconnection/mentor/dto/MatchedMentorResponse.java
src/main/java/com/example/solidconnection/mentor/repository/MentorRepository.java
src/main/java/com/example/solidconnection/mentor/repository/MentoringRepository.java
src/main/java/com/example/solidconnection/mentor/service/MentoringQueryService.java
src/test/java/com/example/solidconnection/mentor/service/MentoringQueryServiceTest.java

- resolves: #478
매칭된 멘티/멘토 정보 조회 기능 구현합니다.
[브루노 pr](https://github.com/solid-connection/api-docs/pull/50)

feat: 매칭된 멘티/멘토 정보 조회 기능 구현

---

docker-compose.dev.yml
docker-compose.prod.yml

- resolves: #495 
[prod 서버에 hotfix로 올린 PR 내용을 dev 서버에도 반영합니다.](https://github.com/solid-connection/solid-connect-server/pull/490)
사실 prod 서버에 올린 PR에서 docker-compose.dev.yml의 경로가 또 잘못되었는데요 ... 이번 PR엔 제대로 반영했습니다

fix: alloy 설정 파일 경로 수정

---

src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
src/main/java/com/example/solidconnection/community/board/controller/BoardController.java
src/main/java/com/example/solidconnection/community/comment/repository/CommentRepository.java
src/main/java/com/example/solidconnection/community/comment/service/CommentService.java
src/main/java/com/example/solidconnection/community/post/repository/PostRepository.java
src/main/java/com/example/solidconnection/community/post/service/PostQueryService.java
src/main/java/com/example/solidconnection/siteuser/controller/SiteUserController.java
src/main/java/com/example/solidconnection/siteuser/domain/UserBlock.java
src/main/java/com/example/solidconnection/siteuser/dto/UserBlockResponse.java
src/main/java/com/example/solidconnection/siteuser/repository/UserBlockRepository.java
src/main/java/com/example/solidconnection/siteuser/service/SiteUserService.java
src/test/java/com/example/solidconnection/community/comment/service/CommentServiceTest.java
src/test/java/com/example/solidconnection/community/post/service/PostQueryServiceTest.java
src/test/java/com/example/solidconnection/siteuser/fixture/UserBlockFixture.java
src/test/java/com/example/solidconnection/siteuser/fixture/UserBlockFixtureBuilder.java
src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java

- resolves: #512
차단 관련 API를 구현하였습니다.
- 로그인한 유저의 차단 목록 조회 API
- 차단 API
- 차단 취소 API
급하게 구현을 하다보니 커밋을 완전 많이 쪼개진 못했는데 그래도 노력은 했습니다 ㅎㅎ..
그래도 커밋 따라가면 이해하기 편하실겁니다!
커뮤니티 부분은 현재 인성님이 수정해주고 계신 거 같아서 최대한 기존코드 유지하면서 로직 추가했습니다!
(커뮤니티 쪽 코드가 엄청 지저분하네요 :smiling_face_with_tear: 앞으로 개선될 것이라고 생각합니다!)
1. 우선 차단을 했을 때 게시글 목록에서 차단한 유저의 게시글은 보이지 않도록 했습니다!
2. 그럼에도 게시글을 조회하려한다면 예외를 던지게 했습니다!
3. 특정 게시글에 차단한 유저의 댓글이 있다면 보이지 않게 했습니다!
관련 명세서 : https://github.com/solid-connection/api-docs/pull/51
만욱님의 요청으로 여기서 변경할 사항은 아니지만.. 로그인하지 않은 유저도 게시글 목록 볼 수 있게 수정했습니다!
너무 간단한 pr이 될 거 같아 그냥 같이 작업했습니다!
우선 siteUser쪽에 구현했는데 괜찮은가요? 커뮤니티쪽에 구현할까도 생각했는데 추후 채팅 등 다른곳에서도 차단이 생길 수 있다고 생각해 가장 범용적으로 사용될 수 있는 siteUser쪽으로 구현했습니다.
우선은 단방향으로 본인이 차단한 유저의 게시글 및 댓글만 보이지 않게 했는데 이래도 문제 없을까요?
여기가 가장 고민이 되었던 지점인데.. 차단한 유저의 댓글에 차단하지 않은 유저의 대댓글이 있다면 어떻게 …

feat: 차단 관련 api 구현
